---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcpregistry-editor-role
rules:
- apiGroups:
  - mcp.opendatahub.io
  resources:
  - mcpregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcp.opendatahub.io
  resources:
  - mcpregistries/finalizers
  verbs:
  - update 