---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcpregistry-admin-role
rules:
- apiGroups:
  - mcp.opendatahub.io
  resources:
  - mcpregistries
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch 