---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcpserver-admin-role
rules:
- apiGroups:
  - mcp.opendatahub.io
  resources:
  - mcpservers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch 