---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcp.opendatahub.io
  resources:
  - mcpcertifiedservers
  - mcpregistries
  - mcpserverpools
  - mcpserverruns
  - mcpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcp.opendatahub.io
  resources:
  - mcpcertifiedservers/finalizers
  - mcpregistries/finalizers
  - mcpserverpools/finalizers
  - mcpserverruns/finalizers
  - mcpservers/finalizers
  verbs:
  - update
- apiGroups:
  - mcp.opendatahub.io
  resources:
  - mcpcertifiedservers/status
  - mcpregistries/status
  - mcpserverpools/status
  - mcpserverruns/status
  - mcpservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
