## Append samples of your project ##
resources:
- mcp_v1_mcpregistry.yaml
- mcp_v1_mcpserver.yaml
- mcp_v1_mcpserverpool.yaml
- mcp_v1_mcpserverrun.yaml
# - mcp_v1_mcpserverdefinition.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
