apiVersion: mcp.opendatahub.io/v1alpha1
kind: McpCatalog
metadata:
  labels:
    app.kubernetes.io/name: mcp-registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: red-hat-ecosystem-mcp-catalog
spec:
  description: Red Hat Ecosystem MCP Catalog
  imageRegistry: https://quay.io/repository/ecosystem-appeng/mcp-catalog
