# yaml-language-server: $schema=../crd/bases/mcp.opendatahub.io_mcpservers.yaml
apiVersion: mcp.opendatahub.io/v1alpha1
kind: McpServer
metadata:
  labels:
    app.kubernetes.io/name: mcp-registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: io-github-manusa-kubernetes-mcp-server-kubernetes-mcp-server
  annotations:
    mcp.opendatahub.io/mcp-catalog: red-hat-ecosystem-mcp-catalog
spec:
  server_detail:
    id: 4a097d31-ea39-43aa-9af5-6f19a7676901
    name: io.github.manusa/kubernetes-mcp-server
    description: Model Context Protocol (MCP) server for Kubernetes and OpenShift
    repository:
      url: https://github.com/manusa/kubernetes-mcp-server
      source: github
      id: '930678258'
    version_detail:
      version: 0.0.1-seed
      release_date: '2025-05-16T19:09:03Z'
      is_latest: true
    packages:
    - registry_name: unknown
      name: manusa/kubernetes-mcp-server
      version: ''
---
apiVersion: mcp.opendatahub.io/v1alpha1
kind: McpServer
metadata:
  labels:
    app.kubernetes.io/name: mcp-registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: io-github-cloudflare-mcp-server-cloudflare
  annotations:
    mcp.opendatahub.io/mcp-catalog: red-hat-ecosystem-mcp-catalog
spec:
  server_detail:
      id: 2ad7c503-7daa-46c8-9295-8a1ed53271a6
      name: io.github.cloudflare/mcp-server-cloudflare
      description: ''
      repository:
        url: https://github.com/cloudflare/mcp-server-cloudflare
        source: github
        id: '895268756'
      version_detail:
        version: 0.0.1-seed
        release_date: '2025-05-16T18:58:05Z'
        is_latest: true
      packages:
      - registry_name: npm
        name: "@cloudflare/mcp-server-cloudflare"
        version: 1.0.0
        package_arguments:
        - description: URL to SSE endpoint for observability
          is_required: true
          format: string
          value: https://observability.mcp.cloudflare.com/sse
          default: https://observability.mcp.cloudflare.com/sse
          type: positional
          value_hint: https://observability.mcp.cloudflare.com/sse
      remotes:
      - transport_type: sse
        url: https://observability.mcp.cloudflare.com/sse
      - transport_type: sse
        url: https://bindings.mcp.cloudflare.com/sse
