apiVersion: mcp.opendatahub.io/v1
kind: McpRegistry
metadata:
  labels:
    app.kubernetes.io/name: mcp-registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: red-hat-ecosystem-mcp-catalog
spec:
  description: Red Hat Ecosystem MCP Catalog
  # TODO(user): Add fields here
