apiVersion: mcp.opendatahub.io/v1alpha1
kind: McpPromotionJob
metadata:
  labels:
    app.kubernetes.io/name: mcp-registry-operator
    app.kubernetes.io/managed-by: kustomize
    mcp.opendatahub.io/mcpstagingarea: staging-area
  name: mcppromotionjob
spec:
  catalogRef:
    name: mcp-catalog
    namespace: mcp-catalog
  servers:
    - cert-server-1
    - cert-server-2
