apiVersion: mcp.opendatahub.io/v1
kind: McpServerRun
metadata:
  name: tavily-server
spec:
  registryRef:
    name: mcp-demo-registry
  replicas: 1
  server-mode: blueprint
  envFrom:
    - secretRef:
        name: mcp-tavily-secret
  mcpServer:
    guardian: false
    proxy: true
    mcpServerRef:
      name: io-github-tavily-ai-tavily-mcp-9wrt9
      namespace: mcp-catalog
